theme: jekyll-theme-cayman
title: Swedish Public Transport Sensor (HASL)
description: This site is for documentation for the Swedish Public Transport Sensor (aka HASL) (formerly Home Assistant SL Platform) 
github:
  zip_url: https://github.com/hasl-platform/integration/zipball/master
  tar_url: https://github.com/hasl-platform/integration/tarball/master
  repository_url: https://github.com/hasl-platform/integration
